project_name: "sw-ai-contest"
model_name: "monologg/koelectra-base-v3-discriminator"
train_path: "data/raw/train.csv"
test_path: "data/raw/test.csv"
save_path: "models/hf_adapter"
predict_path: "data/raw/submission_koelectra_lora.csv"
vectorizer: "TF-IDF"
scale_pos_weight: 1
seed: 42
n_estimators: 100
max_length: 512
batch_size: 8
epochs: 5
num_labels: 2
lr: 5.0e-5
weight_decay: 1.0e-2
