project_name: "sw-ai-contest"
model_name: "prajjwal1/bert-tiny"
train_path: "data/raw/train.csv"
test_path: "data/raw/test.csv"
save_path: "models/hf_checkpoint"
predict_path: "data/raw/baseline_submission.csv"
vectorizer: "TF-IDF"
scale_pos_weight: 1
seed: 42
n_estimators: 100
max_length: 512
batch_size: 16
epochs: 3
num_labels: 2
lr: 5e-5
weight_decay: 0.01
